# Generated by Django 5.1 on 2024-08-31 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('tipo_unidade', models.CharField(choices=[('und', 'Unidade'), ('g', 'Gramas'), ('kg', 'Kilos'), ('ml', 'Mililitros'), ('l', 'Litros'), ('cx', 'Caixa')], default='und', max_length=100)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
    ]
