# Generated by Django 5.1.1 on 2024-09-14 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_perfilusuario_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoPerecivel',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estoque.produto')),
                ('validade', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('estoque.produto',),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0),
        ),
    ]
